### PR TITLE
Fix: remove old temp dir when generating new one from status tool

### LINKED ISSUE #580: Delete old plugin's folders after generating a new temporary folder
I realized that when you click on the **Generate temporary directory** button, under the **Status** tab, it generates a new temporary folder, without deleting the old one. I tried clicking several times, and this is the result:

Therefore, we should search folders with the `wpo_wcpdf_` prefix to delete those plugin's folders different to the new generated temporary folder.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #580

### CODE REVIEW

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

**Review by YordanSoares — COMMENTED** [review]
@alexmigf, now the old folders are not remaining as residual folders.

However, I realized that the fonts break:

image

Maybe should we run the fonts reinstalling after clicking on the **Generate temporary directory** button, what do you think?

**Comment by alexmigf** [comment]
@YordanSoares good catch, because the font from my PDF from testing was really close to the expected one.

**Review by YordanSoares — APPROVED** [review]
✅ Now it works perfectly!

**Pull request merged**
