### PR TITLE
dompdf pre-release patches

### PR DESCRIPTION
**Pull request by Spreeuw**
Taking `dev-master` from the `dompdf` library, which fixes a few issues reported by clients with the current release.

@dpeyou  can you test the output of all templates like Yordan did [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/290#issuecomment-1012548232)?

### CODE REVIEW

**Comment by dpeyou** [comment]
@Spreeuw other than switching to this branch & testing, are there any other steps I needed to be aware of?

**Comment by Spreeuw** [comment]
Nope, that's it, then just follow Yordan's example!

**Comment by Spreeuw** [comment]
I updated the branch to include a big change that is being prepared for inclusion in dompdf 1.2.0, and I found some potention issues. I shared my findings in the PR, hopefully this will not require any template updates on our end 😬 

It seems to stem primarily from `line-height` interpretation differences and the biggest effect of this can be seen in 2 places; the document title (which is shifted down significantly in all documents).

<details>

Before:
document-title-master
After:
document-title-vertical-align
</details>

...and the  item meta (which is spaced much further apart now in **Business**)
<details>

Before:
meta-master

After:
meta-vertical-align
</details>
So perhaps @dpeyou we should put a hold on further testing until this has been addressed?

**Comment by Spreeuw** [comment]
Ok, the last commit seems to fix the issues I was seeing. The document type label ("Invoice") still moves down compared to the current release, and I'm seeing a bit more margin in all our templates, so we should probably adjust our styles somewhat when this is being released

**Pull request merged**
