### PR TITLE
New: Dompdf v3.0.0 upgrade

### PR DESCRIPTION
**Pull request by alexmigf**

### CODE REVIEW

**Review by BrunoPavlinic98 — APPROVED** [review]
I have tried to create and show multiple different documents using domPDF, and send PDF as email attachments. Everything worked as expected.

Therefore - LGTM!

**Review by dwalkerpriv — APPROVED** [review]
Works well with all document downloads and attachments 👍

**Review by YordanSoares — APPROVED** [review]
Tested all our default PDF documents and templates with both the latest version (with `dompdf 2.0.7`) and this PR: Both versions were identical.

These were the templates and document tested:

✅ Simple: Invoice
✅ Simple: Packing Slip
✅ Simple: Credit Note
✅ Simple: Proforma Invoice
✅ Simple: Receipt
✅ Simple Template: Invoice
✅ Simple Template: Packing Slip
✅ Simple Template: Credit Note
✅ Simple Template: Proforma Invoice
✅ Simple Template: Receipt
✅ Business: Invoice
✅ Business: Packing Slip
✅ Business: Credit Note
✅ Business: Proforma Invoice
✅ Business: Receipt
✅ Modern: Invoice
✅ Modern: Packing Slip
✅ Modern: Credit Note
✅ Modern: Proforma Invoice
✅ Modern: Receipt

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

**Review by dpeyou — APPROVED** [review]
I tested this mostly passively, as I have been using for a while with no issues particular to this PR.

**Review by Terminator-Barbapapa — APPROVED** [review]

**Pull request merged**
