### PR TITLE
Break long URLs in different lines if it reaches the available space

### PR DESCRIPTION
**Pull request by YordanSoares**
## Testing long URL's within addresses, order data, item meta and notes area:

image

Closes: #444

### CODE REVIEW

**Review by alexmigf — CHANGES_REQUESTED** [review]
Didn't you forgot to add also to `.wc-item-meta`?

**Comment by alexmigf** [comment]
Forget!

**Review by alexmigf — APPROVED** [review]
:rocket:

**Comment by alexmigf** [comment]
@YordanSoares I think we need to apply this also to the Premium Templates.

**Review by Terminator-Barbapapa — APPROVED** [review]
💯

**Pull request merged**
