### PR TITLE
Check current user role in the `enable_debug` function

### PR DESCRIPTION
**Pull request by MohamadNateqi**
Prevent unauthenticated users to enable debug and error reporting.

### CODE REVIEW

**Review by alexmigf — COMMENTED** [review]
Maybe we could use `user_can_manage_settings()` instead?

**Comment by MohamadNateqi** [comment]
@alexmigf, The `user_can_manage_settings()` function checks for `manage_woocommerce` permission and also allows to change it using a filter.

Do you think it's OK to allow other roles to capabilities to enable the debug?

**Comment by alexmigf** [comment]
Yes, if they are in management roles. I believe that question would also be appropriate for the settings, wouldn't it?

**Review by alexmigf — APPROVED** [review]
LGTM!

**Pull request merged**
