### PR TITLE
Updates DOMPDF to version 1.1.1

### PR DESCRIPTION
**Pull request by alexmigf**

### CODE REVIEW

**Comment by Spreeuw** [comment]
@alexmigf can you check that all our official templates (both free and premium) still work as expected, both on single page (1 small order) and multi-page (1 large order)?

**Comment by alexmigf** [comment]
### Simple

#### Small :heavy_check_mark: 

Captura de ecrã de 2021-12-21 10-11-15

#### Large :heavy_check_mark: 

Captura de ecrã de 2021-12-21 10-11-41


### Simple Premium

#### Small :heavy_check_mark: 

Captura de ecrã de 2021-12-21 10-12-11

#### Large :heavy_check_mark: 

Captura de ecrã de 2021-12-21 10-12-34


### Business

#### Small :heavy_check_mark: 

Captura de ecrã de 2021-12-21 10-13-24

#### Large :heavy_check_mark: 

Captura de ecrã de 2021-12-21 10-14-02


### Modern

#### Small (this doesn't seem fine to me) 

Captura de ecrã de 2021-12-21 10-15-59

#### Large (same as above)

**Comment by Spreeuw** [comment]
> ### Modern
> #### Small (this doesn't seem fine to me)
> 
> Captura de ecrã de 2021-12-21 10-15-59
> #### Large (same as above)

Have you compared this to the output in the current release?

**Comment by alexmigf** [comment]
Current:

Captura de ecrã de 2021-12-21 10-45-44

**Comment by Spreeuw** [comment]
@alexmigf do you want to wait for this fix to be included in dompdf 1.2.0? https://github.com/dompdf/dompdf/pull/2699
I prefer not to have dompdf version specific code/workarounds in the templates if it's just a 'temporary' bug, especially if that means existing custom templates would still break.

Another option is to see if we could apply their fix as a patch (using [cweagans/composer-patche](https://github.com/cweagans/composer-patches) or adding it manually)

**Comment by alexmigf** [comment]
We could revert the footer fix and update DOMPDF to 1.1.1, and if someone complaints about the footer issue we could provide this hack mentioning that 1.2.0 should fix this when it's released.

**Comment by Spreeuw** [comment]
I prefer not to release an update that will break something and then wait for people to complain about it. So the only options for me are:

- Release a fix to the template (with the aforementioned downsides)
- Wait until 1.2.0
- Release with 1.1.1 plus the patch ([dompdf/dompdf#2699](https://github.com/dompdf/dompdf/pull/2699))

**Comment by alexmigf** [comment]
Maybe 1.2.0 isn't too far away? https://github.com/dompdf/dompdf/milestone/23

But option 3 is fine for me too.

**Comment by Spreeuw** [comment]
> Maybe 1.2.0 isn't too far away? https://github.com/dompdf/dompdf/milestone/23

Nobody knows :)

> But option 3 is fine for me too.

Can you check all official templates to see if they produce the same output as 1.0.2?

**Comment by alexmigf** [comment]
> Can you check all official templates to see if they produce the same output as 1.0.2?

Using the patch?

**Comment by Spreeuw** [comment]
yes!

**Comment by alexmigf** [comment]
### Tests using patched branch

#### Simple :heavy_check_mark: 

Single page :heavy_check_mark: 

Captura de ecrã de 2022-01-03 16-41-58

Multi-page :heavy_check_mark: 

Captura de ecrã de 2022-01-03 16-42-51


#### Simple Premium :heavy_check_mark: 

Single page :heavy_check_mark: 

Captura de ecrã de 2022-01-03 16-43-53

Multi-page :heavy_check_mark: 

Captura de ecrã de 2022-01-03 16-44-15


#### Modern :heavy_check_mark: 

Single page :heavy_check_mark: 

Captura de ecrã de 2022-01-03 16-45-05

Just notice here a small difference in left spacing compared to the current DOMPDF version:

Captura de ecrã de 2022-01-03 16-50-13

Multi-page :heavy_check_mark: 

Captura de ecrã de 2022-01-03 16-45-22



#### Business :heavy_check_mark: 

Single page :heavy_check_mark: 

Captura de ecrã de 2022-01-03 16-46-27

Multi-page :heavy_check_mark: 

Captura de ecrã de 2022-01-03 16-46-42

**Comment by Spreeuw** [comment]
> Just notice here a small difference in left spacing compared to the current DOMPDF version:
> 
> Captura de ecrã de 2022-01-03 16-50-13

Can you report this in the dompdf PR? The left blocks have a `min-width: 40mm;` value that seems to be ignored.

**Comment by alexmigf** [comment]
> Can you report this in the dompdf PR? The left blocks have a `min-width: 40mm;` value that seems to be ignored.

Done here: https://github.com/dompdf/dompdf/issues/2702#issuecomment-1004228888

**Comment by alexmigf** [comment]
@Spreeuw is the other way around, I think he is right: https://github.com/dompdf/dompdf/issues/2702#issuecomment-1004790317

**Comment by Spreeuw** [comment]
I see,  I think misinterpreted your screenshots, thinking that the second screenshot was from the patched version! So this is in fact a bug that was introduced in 1.0.2 (and we and our clients didn't notice?) and fixed in 1.1.1+patch?

**Comment by alexmigf** [comment]
Correct, it seems it was already there and nobody saw it.

**Comment by Spreeuw** [comment]
In that case, this patched version seems fine to me. What do you think is the best approach here?

1. Manually patch the bundled version
2. Patch using cweagans/composer-patches 
3. Fork to wpovernight/dompdf and apply the patch there and use that until 1.2.0 is released

**Comment by alexmigf** [comment]
I used number 1 for testing, it's easy and straightforward, I would opt for that one, but I'm open for any.

**Comment by alexmigf** [comment]
Maybe forking is better if they delete the branch?

**Comment by Spreeuw** [comment]
I don't think they will delete the branch unless the changes are merged.
I agree, let's do option 1.

**Comment by Spreeuw** [comment]
@alexmigf I see that you opted for a 4th option that we did not discuss, but this has some side effects:

1. The `whitespace` branch is based on `master` rather than the stable `v1.1.1` release
2. With the `git` composer source, several `.git*` files are included (I guess we could avoid this with a `.gitignore` file in our repo)

Was there a specific reason you opted for this option? Did you encounter any issues trying to apply the patch to `v1.1.1`?

**Comment by Spreeuw** [comment]
@alexmigf for readability I have wrapped your screenshots in collapsible sections 💪 

<details>
  <summary>Click for details!</summary>

```markdown
# A collapsible section with markdown
<details>
  <summary>Click to expand!</summary>
  
  ## Heading
  1. A numbered
  2. list
     * With some
     * Sub bullets
</details>
````

</details>

**Comment by alexmigf** [comment]
@Spreeuw sorry, my fault, I didn't recognize at the time that the branch was derivative from `master`, I thought I was doing 1 the right way but now I understood that not. I will fix that.

**Pull request merged**
