### PR TITLE
COC & VAT descriptions

### LINKED ISSUE #661: VAT number and COC number not printed
The VAT & COC numbers are not printed on the UBL invoice, though the fields are filled in under PDF Invoices > General > Shop VAT Number / Shop Chamber of Commerce Number.

### PR DESCRIPTION
**Pull request by dwalkerpriv**
closes #661 

Adds a descriptions for the COC/VAT numbers settings entered on the General settings page:

Screenshot 2023-11-30 180410

### CODE REVIEW

**Comment by dwalkerpriv** [comment]
@alexmigf one issue that i've been circling is that methods to return the vat number is returning a null even though the field is filled in. I'm referring to this method

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/bcc8a813ba9247386d0f09b73764cb474870b250/includes/documents/abstract-wcpdf-order-document.php#L838-L840

Similarly, the lines here return a null though the respective fields are filled in

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/bcc8a813ba9247386d0f09b73764cb474870b250/ubl/Handlers/Ubl/AddressHandler.php#L48-L49

The COC and VAT don't print in the UBL file. Not sure what's happening here

**Comment by alexmigf** [comment]
@dwalkerpriv I have merged a fix, should be working now.

**Comment by alexmigf** [comment]
Maybe this settings should be in the Pro extension only?

**Comment by dwalkerpriv** [comment]
@alexmigf the COC number is now displaying on the UBL and invoices with your last fix. The VAT number is still returning null though. Does the VAT display on the UBL & invoices on your setup?

**Comment by alexmigf** [comment]
@dwalkerpriv yes, it seems to be working for me.

**Comment by alexmigf** [comment]
@dwalkerpriv do you still need this PR? Also, I think you should add the fields using an hook and not placing them directly in the template.

**Comment by dwalkerpriv** [comment]
@alexmigf this one adds the description of COC/VAT label  in General settings. I've  updated the PR description

**Review by alexmigf — CHANGES_REQUESTED** [review]

**Comment by alexmigf** [comment]
@dwalkerpriv could you review my changes?

**Comment by dwalkerpriv** [comment]
@alexmigf all good on my end 👍

**Pull request merged**
