### PR TITLE
More billing/shipping address visibility options

### LINKED ISSUE #85: add option to always show shipping address on invoice
Change this:
display-shipping-address-old

to this:
display-shipping-address-new

(and do the same for packing slip, proforma etc.)

Existing templates do not support this yet:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/e9ae661705bacd3ca650d769cf6bb9b6a66a2a7d/templates/Simple/invoice.php#L43

so I see two possibilities:

1. We use the [wpo_wcpdf_ships_to_different_address](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/e9ae661705bacd3ca650d769cf6bb9b6a66a2a7d/includes/documents/abstract-wcpdf-order-document-methods.php#L95) filter to return true for all documents with the 'Always' setting enabled.
2. We change the template and accept that legacy templates will not support the option.

Any thoughts?

### PR DESCRIPTION
**Pull request by Spreeuw**
fixes #85

### CODE REVIEW

**Comment by alexmigf** [comment]
Option **Always** only works if they are different.

**Comment by Spreeuw** [comment]
Are you on the "Simple" template? I haven't applied these changes to the other templates yet

**Comment by alexmigf** [comment]
Yes, i am, i saw that.

**Comment by Spreeuw** [comment]
I double checked, works for me on Simple:

Same shipping & billing
1. Always = shows
2. Only when shipping address is different from the billing address = doesn't show

Different shipping & billing
1. Always = shows
2. Only when shipping address is different from the billing address = shows

**Pull request merged**
