### PR TITLE
Update dompdf to dev-master (pre-1.2.0)

### PR DESCRIPTION
**Pull request by Spreeuw**
Our patched 1.1.1 version of dompdf (#251) is throwing a lot of notices, possibly as a result of the fact that we patched 1.1.1 with changes that were based on `master` (rather than 1.1.1). If this version is more stable, we should use that for the release instead.
For testing we should verify that the output of the free Simple template as well as the Simple Premium / Business / Modern templates is consistent with previous versions (just like @alexmigf did [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/251#issuecomment-1004221150))

### CODE REVIEW

**Comment by Spreeuw** [comment]
I'm seeing an issue in the header, when using a large image, the `max-height` style seems to throw the second column off the page.

### 1.0.2




### 1.2.0-dev


Reported here: https://github.com/dompdf/dompdf/issues/2738

**Comment by YordanSoares** [comment]
## Tests run:
### Simple (normal size logo) ✔️

<details>
<summary>Single page</summary> 

PDF:
[simple-single.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7865639/simple-single.pdf)

Document converted to PNG:
simple-single-1

</details>

<details>
<summary>Multi page</summary> 

PDF:
[simple-multi.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7865658/simple-multi.pdf)

Document converted to PNG:
simple-multi-1
simple-multi-2


</details>

### Simple Premium (normal size logo) ✔️

<details>
<summary>Single page</summary> 

PDF:
[simple-premium-single.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7865662/simple-premium-single.pdf)

Document converted to PNG:
simple-premium-single-1

</details>

<details>
<summary>Multi page</summary> 

PDF:
[simple-premium-multi.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7865666/simple-premium-multi.pdf)

Document converted to PNG:
simple-premium-multi-1
simple-premium-multi-2

</details>

### Business (normal size logo) ✔️

<details>
<summary>Single page</summary> 

PDF:
[business-single.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7865690/business-single.pdf)

Document converted to PNG:
business-single-1

</details>

<details>
<summary>Multi page</summary> 

PDF:
[business-multi.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7865719/business-multi.pdf)

Document converted to PNG:
business-multi-1
business-multi-2

</details>

### Modern (normal size logo) ✔️

<details>
<summary>Single page</summary> 

PDF:
[modern-single.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7865684/modern-single.pdf)

Document converted to PNG:
modern-single-1

</details>

<details>
<summary>Multi page</summary> 

PDF:
[modern-muti.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7865687/modern-muti.pdf)

Document converted to PNG:
modern-muti-1
modern-muti-2

</details>

### Simple (big size logo) ❌ 

<details>

PDF:
[simple-big-logo.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7866023/simple-big-logo.pdf)

Document converted to PNG:
simple-big-logo-1

</details>

### Simple Premium (big size logo) ❌ 

<details>

PDF:
[simple-premium-big-logo.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7866024/simple-premium-big-logo.pdf)

Document converted to PNG:
simple-premium-big-logo-1

</details>

### Business (big size logo) ❌ 

<details>

PDF:
[business-big-logo.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7866025/business-big-logo.pdf)

Document converted to PNG:
business-big-logo-1

</details>

### Modern (big size logo) ❌ 

<details>

PDF:
[modern-big-logo.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7866026/modern-big-logo.pdf)

Document converted to PNG:
modern-big-logo-1

</details>

### Simple (big size logo resized) ❌ 

<details>

PDF:
[simple-big-logo-resized.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7866027/simple-big-logo-resized.pdf)

Document converted to PNG:
simple-big-logo-resized-1

</details>

### Simple Premium (big size logo resized) ❌ 

<details>

PDF:
[simple-premium-big-logo-resized.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7866031/simple-premium-big-logo-resized.pdf)

Document converted to PNG:
simple-premium-big-logo-resized-1

</details>

### Business (big size logo resized) ❌ 

<details>

PDF:
[business-big-logo-resized.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7866032/business-big-logo-resized.pdf)

Document converted to PNG:
business-big-logo-resized-1

</details>

### Modern (big size logo resized) ❌ 

<details>

PDF:
[modern-big-logo.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/7866033/modern-big-logo.pdf)

Document converted to PNG:
modern-big-logo-1

</details>

**Comment by YordanSoares** [comment]
## Tests run:
### Simple (normal size logo) ✔️

<details>
<summary>Single page</summary> 

Document converted to PNG:
simple-single

</details>

<details>
<summary>Multi page</summary> 

Document converted to PNG:
simple-multi-1
simple-multi-2


</details>

### Simple Premium (normal size logo) ✔️

<details>
<summary>Single page</summary> 

Document converted to PNG:
simple-premium-single

</details>

<details>
<summary>Multi page</summary> 

Document converted to PNG:
simple-premium-multi-1
simple-premium-multi-2

</details>

### Business (normal size logo) ✔️

<details>
<summary>Single page</summary> 

Document converted to PNG:
business-single

</details>

<details>
<summary>Multi page</summary> 

Document converted to PNG:
business-multi-1
business-multi-2

</details>

### Modern (normal size logo) ✔️

<details>
<summary>Single page</summary> 

Document converted to PNG:
modern-single

</details>

<details>
<summary>Multi page</summary> 

Document converted to PNG:
modern-multi-1
modern-muti-2

</details>

### Simple (big size logo) ❌ 

<details>

Document converted to PNG:
image

</details>

### Simple Premium (big size logo) ❌ 

<details>

Document converted to PNG:
image

</details>

### Business (big size logo) ❌ 

<details>

Document converted to PNG:
image

</details>

### Modern (big size logo) ❌ 

<details>

Document converted to PNG:
image

</details>

### Simple (big size logo resized) ❌ 

<details>

Document converted to PNG:
image

</details>

### Simple Premium (big size logo resized) ❌ 

<details>

Document converted to PNG:
image

</details>

### Business (big size logo resized) ❌ 

<details>

Document converted to PNG:
image

</details>

### Modern (big size logo resized) ❌ 

<details>

Document converted to PNG:
image

</details>

**Comment by Spreeuw** [comment]
applying dompdf#2740 fixes these issue with large images! 🎉

**Pull request merged**
