### PR TITLE
Changed default nonce name for wizard dismissal

### LINKED ISSUE #714: Bug: "I am the wizard" button is not working!
The banner displayed when the plugin is installed for the first time includes a button labeled "I am the wizard." However, this button does not dismiss the banner.

image

### PR DESCRIPTION
**Pull request by brualio**
Closes #714 

The default nonce name `_wpnonce` was causing the conflict, so it was changed to `_wpdismissnonce`.

### CODE REVIEW

**Comment by brualio** [comment]
By the way, there's another dialog that should show up after 100 PDF Downloads. It might be a good idea to update it too, but not sure if here or in another issue.

**Comment by MohamadNateqi** [comment]
> By the way, there's another dialog that should show up after 100 PDF Downloads. It might be a good idea to update it too, but not sure if here or in another issue.

I also agree with this.

**Comment by alexmigf** [comment]
@brualio I agree too, can you do that implementation as well?

**Comment by brualio** [comment]
@alexmigf @MohamadNateqi Alright! The code has been updated.

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

**Review by alexmigf — APPROVED** [review]
LGTM!

**Pull request merged**
