### PR TITLE
New: DOMPDF upgrade to v2.0.4

### PR DESCRIPTION
**Pull request by alexmigf**
This PR upgrades DOMPDF to version [2.0.4](https://github.com/dompdf/dompdf/releases/tag/v2.0.4).

### CODE REVIEW

**Comment by alexmigf** [comment]
@dwalkerpriv @YordanSoares @MohamadNateqi  could you test and see if everything is fine with the PDFs?

**Review by MohamadNateqi — COMMENTED** [review]
@alexmigf It's working correctly for me.
I think you also need to bump the PHP version up to 7.1.

**Comment by MohamadNateqi** [comment]
@alexmigf, I think these lines need to be uncommented:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/1368a0619a5fd54267082acb43b48b83d38deb3d/woocommerce-pdf-invoices-packingslips.php#L168-L170

**Comment by alexmigf** [comment]
@MohamadNateqi why?

**Comment by MohamadNateqi** [comment]
@alexmigf, Since the PHP version has been bumped up to 7.2, and we only prevent the execution if the version is lower than 5.6 [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/1368a0619a5fd54267082acb43b48b83d38deb3d/woocommerce-pdf-invoices-packingslips.php#L163), don't we need to update it from 5.6 to 7.2?
Maybe I am missing something here?

**Comment by alexmigf** [comment]
@MohamadNateqi yes, maybe that `5.6` needs to be changed.

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

**Review by YordanSoares — APPROVED** [review]
Tested all our default PDF documents and templates with both the latest version and `dompdf-2.0.4-upgrade`:

✅ Simple: Invoice
✅ Simple: Packing Slip
✅ Simple: Credit Note
✅ Simple: Proforma Invoice
✅ Simple: Receipt
✅ Business: Invoice
✅ Business: Packing Slip
✅ Business: Credit Note
✅ Business: Proforma Invoice
✅ Business: Receipt
✅ Modern: Invoice
✅ Modern: Packing Slip
✅ Modern: Credit Note
✅ Modern: Proforma Invoice
✅ Modern: Receipt
✅ Simple Template: Invoice
✅ Simple Template: Packing Slip
✅ Simple Template: Credit Note
✅ Simple Template: Proforma Invoice
✅ Simple Template: Receipt

## Some remarks:

- I had to add this fix manually to be able to test the Receipt: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/681.
- I realized that the Receipt need some tweaks on the premium templates, since the totals display has issues (not related with this PR):
   
   
image

**Comment by alexmigf** [comment]
> I realized that the Receipt need some tweaks on the premium templates, since the totals display has issues (not related with this PR):

@YordanSoares I'm not able to replicate this. Which steps did you took to see this error?

**Review by dwalkerpriv — APPROVED** [review]
Tested on all documents with all templates 👍

**Pull request merged**
