### PR TITLE
New: PDFJS v3.11.174 upgrade

### PR DESCRIPTION
**Pull request by alexmigf**
PDFJS version 4 uses JavaScrfipt Modules, we might need to change our implementation a bit, we should do that in the near future: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/784

### CODE REVIEW

**Comment by MohamadNateqi** [comment]
Getting this:

image

**Comment by alexmigf** [comment]
I have updated both files, maybe it's cache? I'm not having that error.

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

Sorry! Apparently, my browser refuses to clear the cache completely, even though I ask for it! I tried using another browser, and it is working well.

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

**Pull request merged**
