### PR TITLE
Fix: string encoding issues in PDF

### LINKED ISSUE #567: Issues with string encoding
Some users are [reporting](https://wordpress.org/support/topic/the-font-in-hebrew-shows-question-marks/) issues with encoding chars, this is happening because we made a change [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/557).

### PR DESCRIPTION
**Pull request by alexmigf**
closes #567

### CODE REVIEW

**Review by YordanSoares — APPROVED** [review]
✅ LGTM!

### Testing with the mPDF extension and the latest public release:

image


### Testing with the mPDF extension and the branch from this PR: 

image

**Comment by alexmigf** [comment]
@YordanSoares can you also test other chars, like Romanian?

**Comment by YordanSoares** [comment]
@alexmigf yes, it is working correctly for Rumanian:

image

I also tested the Unicode extension for Chinese, Japanese, and Korean, and it's working correctly, too.

**Review by MohamadNateqi — APPROVED** [review]
LGTM!
Tested on some languages, and it works fine.

**Comment by alexmigf** [comment]
Customer also approved the fix. Thank you for your reviews!

**Pull request merged**
