### PR TITLE
New: bumps WooCommerce min version to 3.3

### PR DESCRIPTION
**Pull request by alexmigf**
Following the same bump for the next Pro extension release, I think we should also do the same here.

### CODE REVIEW

**Review by MohamadNateqi — CHANGES_REQUESTED** [review]
These can also be removed:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/96fef46aa1a28b8979680fea2dc2eb0dd717be21/includes/class-wcpdf-admin.php#L47-L49

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/96fef46aa1a28b8979680fea2dc2eb0dd717be21/includes/documents/abstract-wcpdf-order-document-methods.php#L791-L793

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

**Comment by MohamadNateqi** [comment]
This also needs to be updated:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/74b54ff386be9b65b7695e4cadb3bd98e4895631/woocommerce-pdf-invoices-packingslips.php#L12

**Comment by MohamadNateqi** [comment]
I understood that the `get_order_discount` method used below no longer exists in the Woo plugin. We need to remove them in this PR or maybe another:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/96fef46aa1a28b8979680fea2dc2eb0dd717be21/includes/documents/abstract-wcpdf-order-document-methods.php#L965-L972
All of the usage of this method which is in the Template plugin is only for getting `total`.

<hr>

Maybe this also should be removed:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/96fef46aa1a28b8979680fea2dc2eb0dd717be21/includes/documents/abstract-wcpdf-order-document-methods.php#L228-L232

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/96fef46aa1a28b8979680fea2dc2eb0dd717be21/includes/documents/abstract-wcpdf-order-document-methods.php#L241-L244

**Comment by alexmigf** [comment]
> Maybe this also should be removed:

I think we should keep, it's using getters.

**Comment by alexmigf** [comment]
> I understood that the get_order_discount method used below no longer exists in the Woo plugin. We need to remove them in this PR or maybe another:

Done.

**Review by MohamadNateqi — APPROVED** [review]
Perfect!

**Pull request merged**
