### PR TITLE
Remove path to generic_document.png

### PR DESCRIPTION
**Pull request by MohamadNateqi**
There is no `generic_document.png` in the images, while it has been used for the documents icon.

### CODE REVIEW

**Review by alexmigf — COMMENTED** [review]
Maybe having that file back would be better? I made the new ones, I can do something simple.

**Comment by MohamadNateqi** [comment]
That would be great.
I'm no expert in creating these SVGs, so I just removed it.

**Comment by alexmigf** [comment]
What about this?

generic

**Comment by MohamadNateqi** [comment]
This is great, I'll add it. Thanks

**Comment by alexmigf** [comment]
@MohamadNateqi consider reverting the last commit, merging `main`, and then making the changes afterward.

**Comment by MohamadNateqi** [comment]
@alexmigf Done.

**Comment by alexmigf** [comment]
The parent constructor must be called before setting properties in the derived classes.

Screenshot from 2024-10-04 08-14-09

**Comment by alexmigf** [comment]
Or maybe just move the icon after it.

**Comment by alexmigf** [comment]
After reconsidering, it might be best to hold off on this change for now, as it will affect the Pro extension documents.

**Comment by MohamadNateqi** [comment]
As you said, I think the parent constructor should be called first, but for now, I can revert the last commit, and we can fix it later in another issue.

**Review by alexmigf — APPROVED** [review]

**Pull request merged**
