### PR TITLE
Tweak: updates Upgrade tab extension features

### PR DESCRIPTION
**Pull request by alexmigf**

### CODE REVIEW

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

**Review by dwalkerpriv — APPROVED** [review]
Works well and has a nice UI too. The only small thing I could suggest would be moving the Currently install text next to the plugin name at the top. Not a biggy though 👍

**Comment by alexmigf** [comment]
@dwalkerpriv the changes are only in text, please see the modifications.

**Comment by dwalkerpriv** [comment]
@alexmigf the text is good as well 👍

**Pull request merged**
