### PR TITLE
New: DOMPDF v2.0.8 upgrade

### PR DESCRIPTION
**Pull request by alexmigf**
> New: sabre/xml v2.2.7 upgrade

The new DOMPDF version introduces only minor corrections and should not present any noticeable differences from the previous version.

We should test the XML upgrade specifically for compatibility with the UBL format.

### CODE REVIEW

**Review by MohamadNateqi — APPROVED** [review]
I created all types of documents with all templates and also tried the UBL; all of them are working correctly on my end.

**Review by dpeyou — APPROVED** [review]
I mostly spent time testing the UBL. I think it is fine.
I have been testing other things while using the PDF Invoices and all seems fine.

**Review by dwalkerpriv — APPROVED** [review]
works for all the documents on my end 👍

**Review by YordanSoares — APPROVED** [review]
Tested all our default PDF documents and templates with both the latest version and this PR:

✅ Simple: Invoice
✅ Simple: Packing Slip
✅ Simple: Credit Note
✅ Simple: Proforma Invoice
✅ Simple: Receipt
✅ Business: Invoice
✅ Business: Packing Slip
✅ Business: Credit Note
✅ Business: Proforma Invoice
✅ Business: Receipt
✅ Modern: Invoice
✅ Modern: Packing Slip
✅ Modern: Credit Note
✅ Modern: Proforma Invoice
✅ Modern: Receipt
✅ Simple Template: Invoice
✅ Simple Template: Packing Slip
✅ Simple Template: Credit Note
✅ Simple Template: Proforma Invoice
✅ Simple Template: Receipt

**Comment by alexmigf** [comment]
Version 3.0.0 was released sooner than expected, so we are skipping this version.

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/797

**Pull request closed without merging**
