### PR TITLE
New: updates DOMPDF to v2.0.7

### LINKED ISSUE #767: DOMPDF v2.0.7 upgrade
DOMPDF v2.0.7 upgrade

### PR DESCRIPTION
**Pull request by alexmigf**
closes #767

### CODE REVIEW

**Review by MohamadNateqi — APPROVED** [review]
Working correctly on my end.

**Review by dwalkerpriv — APPROVED** [review]
Works for all the documents. Also, I'm not sure if it's just me, but the font seems slightly different. If it is - I like it :)

**Review by Terminator-Barbapapa — APPROVED** [review]

**Review by dpeyou — APPROVED** [review]
I think it's good to go :+1:

**Review by YordanSoares — APPROVED** [review]
LGTM!

**Pull request merged**
