### PR TITLE
New: filter to change role capabilities to access plugin settings

### LINKED ISSUE #476: Allow filtering role capabilities to access plugin settings
Currently we only provide access to the plugin settings to roles with `manage_woocommerce` capabilities, but would be good to be possible to filter those capabilities.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #476

### CODE REVIEW

**Comment by Terminator-Barbapapa** [comment]
At the moment this only affects a small part of the functionality (for instance viewing the preview). But using this new filter does not allow users with other capabilities than `manage_woocommerce` to view and edit settings.

**Comment by alexmigf** [comment]
@Terminator-Barbapapa fixed

**Review by Terminator-Barbapapa — CHANGES_REQUESTED** [review]
This will let you change the required user capability to view and edit settings, but it won't allow you to add capabilities that are allowed to view and edit settings.

For instance if I want to allow a vendor that has the capability to `manage_product` to edit settings I can't (without an administrator losing his ability to edit settings).

**Comment by alexmigf** [comment]
> For instance if I want to allow a vendor that has the capability to manage_product to edit settings I can't (without an administrator losing his ability to edit settings).

You can, just load the current user using `wp_get_current_user()` inside the filter and do the required check for it, the others can keep the default capability.

**Comment by alexmigf** [comment]
Since `add_submenu_page` accepts only [one capability](https://developer.wordpress.org/reference/functions/add_submenu_page/), we are a bit limited here.

**Comment by Terminator-Barbapapa** [comment]
Couldn't we rewrite `user_can_manage_settings()` like this:

```
public function user_can_manage_settings() {
	$user_can_manage_settings = false;	
	$capabilities = apply_filters( 'wpo_wcpdf_settings_user_role_capabilities', array(
		'manage_woocommerce',
	) );
	foreach ( $capabilities as $capability ) {
		if ( current_user_can( $capability ) ) {
			$user_can_manage_settings = $capability;
			break;
		}
	}
	return $user_can_manage_settings;
}
```

So it either returns a capability or `false`. We can then call it in the `menu()` function like this:

```
public function menu() {
	$parent_slug = 'woocommerce';
	
	$this->options_page_hook = add_submenu_page(
		$parent_slug,
		esc_html__( 'PDF Invoices', 'woocommerce-pdf-invoices-packing-slips' ),
		esc_html__( 'PDF Invoices', 'woocommerce-pdf-invoices-packing-slips' ),
		$this->user_can_manage_settings(),
		'wpo_wcpdf_options_page',
		array( $this, 'settings_page' )
	);
}
```

That way the filter gets simpler to user. You just set the capabilities you want to allow to edit settings. Like this:

```
add_filter( 'wpo_wcpdf_settings_user_role_capabilities', function( $capabilities ) {
	$capabilities = array( 'manage_woocommerce', 'manage_product' );
	return $capabilities;
}, 10, 1 );
```

**Comment by alexmigf** [comment]
@Terminator-Barbapapa I believe you can't have a `bool` value on `add_submenu_page()`, but you gave me an idea.

**Comment by Terminator-Barbapapa** [comment]
The above code worked for me without issues. But maybe I missed something.

**Comment by alexmigf** [comment]
I know it works, but I'm not sure we gain much using an array:

* You can only pass one capability to `add_submenu_page()` and using your suggestion we can miss the correct one;
* If you're using `false` in `user_can_manage_settings()` if the user hasn't any of the passed capabilities you're passing `false` to `add_submenu_page()` when it expects a `string`.

I think we should keep using a single `string` value as before.

**Comment by Terminator-Barbapapa** [comment]
I agree that returning `false` might not be the best thing to do (although I think it doesn't causes issues when calling `add_submenu_page()`)

But I think we can simplify it to the following:

```
public function user_settings_capability() {
	$user_capability       = 'manage_woocommerce';
	$capabilities_to_check = apply_filters( 'wpo_wcpdf_settings_user_role_capabilities', array( $user_capability ) );

	foreach ( $capabilities_to_check as $capability ) {
		if ( current_user_can( $capability ) ) {
			$user_capability = $capability;
			break;
		}
	}
	return $user_capability;
}
```

As I don't think we need a filter for the default capability. The `manage_woocommerce` capability should always allow viewing/editing of the settings.

**Comment by alexmigf** [comment]
I agree, but I still think we don't need an array and the previous code was better.

**Comment by Terminator-Barbapapa** [comment]
Which array do you mean? The `$user_capability` variable will always return a string. And the `$capabilities_to_check` variable also contained an array in your previous code, where it was called `$custom_capabilities`.

**Comment by alexmigf** [comment]
I reverted my last commit from today, check the previous code.

**Comment by Terminator-Barbapapa** [comment]
I see. But that would make the filter less intuitive to use use again.

**Comment by alexmigf** [comment]
Can you explain?

**Comment by Terminator-Barbapapa** [comment]
I think ideally you want to have a filter were you just add the capabilities that can view/edit settings. So just something like this:

```
add_filter( 'wpo_wcpdf_settings_user_role_capabilities', function( $caps ) {
	return array( 'manage_shop_order_terms', 'manage_product' );
}, 10, 1 ); 
```

**Comment by alexmigf** [comment]
Ultimately you just need one capability to be valid under `current_user_can`, once that happens settings should be accessible. If it's not working with `manage_woocommerce` you just need to filter and return a different one, because in the end you just need one.

The array check [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/477#issuecomment-1436638436) just returns one value, you could have 20 capabilities but if the first is valid doesn't matter how many you have, that's why I think just validating one from the beginning should be enough and turns the code more clear and simple. Was my fault because initially I was thinking using an array would be good, but after your first review I saw that I was wrong, and maybe that's why Ewout was using just like that as well. I think we don't need to complicate this, we could also use the [filter](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/477#issuecomment-1431234848) to create specific user role scenarios.

**Comment by Terminator-Barbapapa** [comment]
I understand that only one capability has to be valid to view/edit the settings. And I think your initial code works great. I just think it makes the filter more difficult to use. For instance let's say I want to provide shop managers and vendors access to the settings.

With the current setup the filter would look like this:

```
add_filter( 'wpo_wcpdf_settings_user_role_capabilities', function( $capabilities ) {
	$user = wp_get_current_user();
	if ( in_array( 'shop_manager', (array) $user->roles ) ) {
		$capabilities = 'manage_shop_order_terms';
	} elseif ( in_array( 'dc_vendor', (array) $user->roles ) ) {
		$capabilities = 'manage_product';
	}
	return $capabilities;
}, 10, 1 );
```

With the proposed setup it would look like this:

```
add_filter( 'wpo_wcpdf_settings_user_role_capabilities', function( $capabilities ) {
	return array( 'manage_shop_order_terms', 'manage_product' );
}, 10, 1 ); 
```

**Comment by alexmigf** [comment]
Done, please leave your review.

**Review by Terminator-Barbapapa — APPROVED** [review]
🚀

**Pull request merged**
