### PR TITLE
Fix Composer configuration

### PR DESCRIPTION
**Pull request by szepeviktor**
Match reality and Composer config.

1. ubl/ is real PSR-4
2. includes/ are WPCS thus need "classmap"

Extra: add license to Composer config.

#563

### CODE REVIEW

**Comment by szepeviktor** [comment]
💡 It would be very nice to convert includes to PSR-4.

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

**Comment by alexmigf** [comment]
Thank you @szepeviktor !

I have included your changes [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/797), so I'm closing this PR.

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request closed without merging**
