### PR TITLE
New: PDFJS v4.3.136 upgrade

### LINKED ISSUE #784: Migrate PDFJS to version 4
Currently our implementation supports only PDFJS 3, we should migrate our code to support version 4.

### PR DESCRIPTION
**Pull request by MohamadNateqi**
close #784

### CODE REVIEW

**Review by alexmigf — APPROVED** [review]
I was expecting to be more complicated. Great work!

**Review by BrunoPavlinic98 — APPROVED** [review]
LGTM!

**Review by dwalkerpriv — APPROVED** [review]
Works on my end for all of the documents. Sending the documents via email and cloud storage works as before, too 👍

**Review by YordanSoares — APPROVED** [review]
✅ LGTM!

**Pull request merged**
